### ISSUE TITLE
速率下降

### ISSUE THREAD

**Issue by Coffee-kitten** [zephyrchien/realm#11]
长时间转发后 速率会下降 kill掉后重新转发又恢复正常

**Comment by zephyrchien** [comment]
@Coffee-kitten 请提供一下复现方式

**Comment by Coffee-kitten** [comment]
> @Coffee-kitten 请提供一下复现方式
./realm -n 65535 -d -c realm.toml 配置转发9条

**Comment by Coffee-kitten** [comment]
> @zephyrchien ./realm -n 65535 -d -c realm.toml 配置转发8条左右

**Comment by Coffee-kitten** [comment]
> > @zephyrchien ./realm -n 65535 -d -c realm.toml 配置转发8条左右

使用TOML Example实例配置进行配置

**Comment by zephyrchien** [comment]
日志里有报错么

连接数是否异常？

**Comment by Coffee-kitten** [comment]
> 日志里有报错么
> 
> 连接数是否异常？

日志正常 一个端口tcp连接数1500左右

**Comment by zephyrchien** [comment]
信息太少了，没法定位问题

可能是由不正确的客户端实现导致的。Realm不会主动关闭连接，如果客户端不主动关闭连接，连接就会一直保持，久而久之就会积累大量不活跃的连接。这是正常行为，也未必会造成性能问题；如果主动设置超时的话反而会影响长连接。

也有可能是连接太多，消耗了太多内核内存(?) 每个连接最多会用到64k内核内存，不过同时转发1k连接也就用掉64m，转发完就释放掉了

**Comment by Coffee-kitten** [comment]
> 信息太少了，没法定位问题
> 
> 可能是由不正确的客户端实现导致的。Realm不会主动关闭连接，如果客户端不主动关闭连接，连接就会一直保持，久而久之就会积累大量不活跃的连接。这是正常行为，也未必会造成性能问题；如果主动设置超时的话反而会影响长连接。
> 
> 也有可能是连接太多，消耗了太多内核内存(?) 每个连接最多会用到64k内核内存，不过同时转发1k连接也就用掉64m，转发完就释放掉了

谢谢老哥分析 我再捣鼓测试下

**Comment by zephyrchien** [comment]
5f2b093 50a92f5
