### ISSUE TITLE
关于tfo

### ISSUE THREAD

**Issue by Coffee-kitten** [zephyrchien/realm#12]
想请教一下作者 tfo是默认开启的吗 当前使用的是配置文件形式  如需关闭 格式是否是fast_open = false 貌似找到上次掉速原因 跟系统内核参数tcp_fastopen_blackhole_timeout_sec有关

**Comment by zephyrchien** [comment]
github自动发布的版本并没有把tfo模块编译进去

**Comment by Coffee-kitten** [comment]
zero copy是编译进去了吗

**Comment by zephyrchien** [comment]
https://github.com/zephyrchien/realm#build-options

**Comment by Coffee-kitten** [comment]
明白了 感谢解答
