### ISSUE TITLE
希望支持自动移除故障节点

### ISSUE THREAD

**Issue by fishg** [zephyrchien/realm#13]
{
      "listen": ["0.0.0.0:5000","0.0.0.0:4002","0.0.0.0:5003"],
      "upstreams": ["1.1.1.1:1234","8.8.8.8:443"],
      "fail_timeout": 1800
}

希望能支持类似ng的upstream方式,多端口监听，随机选择upstream，如果upstream tcp链接超时或者refuse，这个节点就禁用fail_timeout的时长

**Comment by zephyrchien** [comment]
可以支持。 以后还可以根据host/sni/path 来分流。

~~不过我目前对这些功能都不感兴趣~~

**Comment by luodaoyi** [comment]
> 可以支持。 以后还可以根据host/sni/path 来分流。
> 
> ~不过我目前对这些功能都不感兴趣~

我觉得host/sni还是有用的... 
path确实没啥用
