### ISSUE TITLE
code=killed, signal=ABRT

### ISSUE THREAD

**Issue by BrunuhVille** [zephyrchien/realm#14]
● realm.service - realm
     Loaded: loaded (/etc/systemd/system/realm.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: signal) since Thu 2022-04-07 17:50:09 CST; 4s ago
    Process: 760 ExecStartPre=/bin/sh -c ulimit -n 51200 (code=exited, status=0/SUCCESS)
    Process: 761 ExecStart=/usr/local/bin/realm -c /etc/realm/config.json (code=killed, signal=ABRT)
   Main PID: 761 (code=killed, signal=ABRT)
        CPU: 4ms

想问下这种情况，可能是什么问题呢，重启也没有效果

**Comment by zephyrchien** [comment]
@BrunuhVille 打开日志， 再手动运行看看

**Comment by BrunuhVille** [comment]
是端口相同冲突了。。
