### ISSUE TITLE
请问是否可能支持指定出口线路

### ISSUE THREAD

**Issue by kdurov** [zephyrchien/realm#2]
多线接入的转发机器，能否在不修改路由表/iptables的情况下支持指定出口？
如果比较麻烦，需要改动不少代码的话就当这个issue不存在吧😅

谢谢

**Comment by zephyrchien** [comment]
你是说指定出口ip吗，这个需求还挺常见的。我明天就把它加上

**Comment by kdurov** [comment]
对。三线的中转机器还挺常见的。
同一落地不同时段不同线路轮流炸。如果能不同监听端口走不同出口IP的话，对于高峰期应该挺有用的吧。


另外想请教下解析是用什么公共DNS解析的？
转发机上我用的本地DNS服务器，强行修改了几个解析结果，貌似没能正确解析。

**Comment by zephyrchien** [comment]
> 另外想请教下解析是用什么公共DNS解析的？ 转发机上我用的本地DNS服务器，强行修改了几个解析结果，貌似没能正确解析。

trust-dns默認用的Google的DNS

> Creates a default configuration, using 8.8.8.8, 8.8.4.4 and 2001:4860:4860::8888, 2001:4860:4860::8844 (thank you, Google).

**Comment by zephyrchien** [comment]
5a30531 需要指定through參數，可以填IP或者IP:端口(僅限UDP; TCP不能複用同IP同端口)

**Comment by kdurov** [comment]
谢谢热心大佬了。

经过试验，发现through参数里面如果是v6地址不带端口的话，不能加上[]。

**Comment by zephyrchien** [comment]
> 经过试验，发现through参数里面如果是v6地址不带端口的话，不能加上[]。

被你發現了，我解析`through`的時候直接用了`parse`. 其實這和 zhboner/realm#36 是同樣的原因。另外你也可以加上端口，寫成[::1]:0，這樣就會當作地址來處理。

==========
0167737 現在`through`可以直接解析[::1]這種形式的IP了

**Comment by zephyrchien** [comment]
>另外想请教下解析是用什么公共DNS解析的？
转发机上我用的本地DNS服务器，强行修改了几个解析结果，貌似没能正确解析。

现在可以自定义DNS服务器了，Linux上默认用`/etc/resolv.conf`里定义的DNS。(前提是编译的时候启用了`trust-dns`，默认是启用的)

如果编译时禁用了`trust-dns`，那么就会用rust标准库里的解析器，读取`/etc/resolv.conf`，同步解析。
