### ISSUE TITLE
ipv6转ipv4

### ISSUE THREAD

**Issue by reizhi** [zephyrchien/realm#5]
realm 目前似乎不能像 socat 那样监听本地 ipv6 端口，转发到远程 ipv4 端口。
测试了使用 through 绑定 ipv4 不通。但是本地 ipv6 到远程 ipv6 是没问题。

**Comment by zephyrchien** [comment]
请提供一下日志，方便排查问题

> 不能像 socat 那样监听本地 ipv6 端口，转发到远程 ipv4 端口

至少我本地测试是可以的:
```shell
realm -l '[::]1:10000' -r '127.0.0.1:20000'
```
```shell
iperf3 -s -p 20000
```
```shell
iperf3 -c ::1 -p 10000 
```

**Comment by reizhi** [comment]
没有日志和输出

服务器 `iperf3 -s`
本地 `iperf3 -c 2409:******:e274 -p 5201`

正常
****
服务器 `iperf3 -s` `./realm -l '[::1]:6201' -r '127.0.0.1:5201'`
本地 `iperf3 -c 2409:*******:e274 -p 6201`

iperf3: error - unable to connect to server: Connection refused

`nmap -6 -p5201 2409:****:e274` > open
`nmap -6 -p6201 2409:****:e274` > closed

其他信息：IPv4 为内网地址，只有少数端口与外网相通（即NAT VPS）。IPv6 为公网全通。

**Comment by zephyrchien** [comment]
目前命令行还不能设置日志，需要从配置文件启动
```shell
realm -c config.json
```
```json
// config.json
{
  "log": {
    "level": "debug",
    "output": "stdout"
  },
  "endpoints": [
    {
      "local": "[::1]:6201",
      "remote": "127.0.0.1:5201"
    }
  ]
}
```

**Comment by reizhi** [comment]
非常遗憾，还是没有输出。
只有启动的 inited 消息。

**Comment by zephyrchien** [comment]
我错了。。地址应该写成`[::0]:6201`, `[::1]`监听的是loopback :sweat:

**Comment by reizhi** [comment]
😅他非常奇怪的自己好了，十分感谢大佬抽空指导。
