### ISSUE TITLE
Support for websocket or other Tunnel protocol

### ISSUE THREAD

**Issue by MikoyChinese** [zephyrchien/realm#6]
Support for websocket or other Tunnel protocol.

**Comment by zephyrchien** [comment]
I would love to, but I'm afraid that is not a goal of realm. Maybe you could try [this repo](https://github.com/zephyrchien/midori)?

**Comment by MikoyChinese** [comment]
Ok, I just wanna use this tool as same as gost. Thx, I will try midori firstly.
